### ISSUE TITLE
compose_cancelled is not triggered

### ISSUE THREAD

**Issue by zvikae** [KartikTalwar/gmail.js#348]
Hi.

I added:
gmail.observe.on("compose_cancelled", function(id, url, body, xhr) {
      debugger
 });
And when I close the compose window, the function isn't fired.

Someone can help me please?

Thanks.

**Comment by josteink** [comment]
If that is production code, it obviously should be `debugger();`, but I'm guessing it's shortened?

It worked for me when I merged it in. Have you tried waiting for the "load" event before registering other event-handlers? Could you show us more of your code, to see it in context?

cc: @yellowandy

**Comment by zvikae** [comment]
I have listener when compose window has opened and inside it, another button created near the 'send' button, for open/close some modal.

gmail.observe.on("compose", function(id, url, body, xhr) {
        composes_window = gmail.dom.composes().length
        compose_ref = gmail.dom.composes()[composes_window - 1];
        var templates_button = '<div id="sales" style="cursor: pointer">Templates</div>';
        gmail.tools.add_compose_button(compose_ref, templates_button, function() {
          $("#templates-list-wrapper").toggle();
        }, 'Custom Style Classes');
    });

The secod function is:
      gmail.observe.on("compose_cancelled", function(id, url, body, xhr) {
      $("#templates-list-wrapper").hide();
    });

This listener is for close the modal opened, but nothing happened

**Comment by josteink** [comment]
I've written the following test-code and that works for me:

````javascript
    gmail.observe.on("compose_cancelled", () => {
        console.log("CC: on!");
    });

    gmail.observe.after("compose_cancelled", () => {
        console.log("CC: after!");
    });

    gmail.observe.before("compose_cancelled", () => {
        console.log("CC: before!");
    });
````

The result of this when closing is a compose-window is:

````
CC: on!
````

The event fires, but only for the `on` observer. Are you sure you're using the right observer-method?

If you still can't make it work, maybe @yellowandy could help dig into what's going wrong?

**Comment by zvikae** [comment]
@josteink 
Still not working.
I've added also the 'load' observe and the compose_cancelled inside and it's not working.
I opened the compose and then I close it and nothing.
@yellowandy Can you help me please?

Thanks.

**Comment by topealabi** [comment]
same issue, I'm using the most recent version of gmail.js, would really appreciate some insight

**Comment by josteink** [comment]
Are you guys using NodeJS-style `require()` loading, or regular script-loading and waiting for objects to become available?

Not sure if it matters, but for me, NodeJS-style `require()` works fine. Would be interesting to see if people's experience differs based on loading-technique.

**Comment by topealabi** [comment]
I'm using regular script-loading

**Comment by josteink** [comment]
I don't have any boilerplate-handy, although I have considered creating it.

In short:

* Use NodeJS and npm to install packages.
* In the source of your injected script, simply say `var Gmail = require("gmail-js").Gmail;` instead of trying to load it as a secondary script (and all that messy stuff with trying to probe when it becomes available, etc etc). It becomes available the second you run that line. Simple. Done.
* *Browsers* don't understand `require()`, so use [browserify](http://browserify.org/) (or webpack) to bundle the script and all its dependencies together into one final JS-file.
* This JS-file is the one you inject into the Gmail-page from your content-script, not the original, which at this point should be considered "uncompiled".

It's not that hard really. Please, give it a spin and see if that works out better for you.

**Comment by topealabi** [comment]
Hi @josteink I've been working with browserify for about 3 hrs now and I'm having issues reproducing even the basic boilerplate functionality. the steps I took were

- npm install -g browserify
- npm install gmail-js
- added content.js, main.js, and manifest.json files
- browserify main.js -o bundle.js
- change content.js to load bundle.js

You can see the relevant files here: https://gist.github.com/topealabi/23645489147b9d50c755268a592f0445

I get error  'Uncaught ReferenceError: refresh is not defined(…)'

**Comment by topealabi** [comment]
@zvikae I was able to call compose_cancelled within a compose observer:

gmail.observe.on("compose", function(id, url, body, xhr) {
        console.log("compose opened");
        gmail.observe.on("compose_cancelled", function(){ console.log("cancelled") })
      });

For anyone else that may see this I still think js concatenation would improve the consistency of performance for this libraray

**Comment by josteink** [comment]
So basically we should make a NodeJS boilerplate too then?

**Comment by josteink** [comment]
So basically you think we should make a NodeJS boilerplate too and then this issue should be considered resolved?

@topealabi Do you feel like you're up for the task? You make the boilerplate and I'll add the link :)

**Comment by zvikae** [comment]
@topealabi Thanks, but your solution is not working also, even inside 'compose' event.

@josteink The 'compose_cancelled' is the only observer that not working for me, all the rest is. So, maybe it is problem with this specific observer - 'compose_cancelled

**Comment by josteink** [comment]
@zvikae topealabi has made one error in his description, which may cause you problems.

He said he set the browserified JS-file as a content-script. This is not what you should do. You should use your existing content-script to load/inject the browserified script, and only that script.

Can you try that and see if that solves the problem for you?

**Comment by zvikae** [comment]
@josteink @topealabi 
Actually, it was my mistake. I had the 0.5 version of gmail.js.
I updated now to 0.6.0 and it's working both inside 'compose' observer and outside 'compose' observer function.

Thanks all!

**Comment by josteink** [comment]
Ok. In that case I'll consider this case closed.

@topealabi If you want to create a NodeJS boilerplate repo, feel free, and please *do* send a PR back here with the link :)

**Comment by topealabi** [comment]
Thanks guys, I'd be glad to contribute if I get the chance

**Comment by Osmosis311** [comment]
This isn't working for me, and I'm not sure why, because I see the handler being registered.  Here is what I see in my console:
`set compose cancelled callback`

and that comes from this line in the code:

```
else if(action === "compose_cancelled") {
            console.log("set compose cancelled callback");
            api.tracker.composeCancelledCallback = callback;
        }
```

so clearly the callback is being registered, it's just not firing.  Any advice?

**Comment by josteink** [comment]
@Osmosis311: Can you provide a more complete code-sample which demonstrates this behaviour?

If you can reproduce this with simply editiing the extension.js-file in the following boilerplate project, we'll at least have a common understanding to work from:

https://github.com/josteink/gmailjs-node-boilerplate

**Comment by morungos** [comment]
I know it's late but I've just arrived at this issue too.

I've found one context where `compose_cancelled` doesn't get fired, notably the inline compose panels at the end of a conversation. All others seem okay, but I don't get the cancel here. 

There's the slight complexity that there are two cases:

1. Explicit cancel (still no compose_cancelled)
2. Implicit cancel by switching back to the inbox -- the draft remains in play, and arguably the compose is still "pending" in some form

They're different cases, even though `compose_cancelled` doesn't happen in either. For type 1, I think it totally should. The other might need more consideration.

**Comment by morungos** [comment]
@josteink For clarity, I should probably make a new issue to make a clean break from the inconclusive discussions in this one. Does that make sense? Then I can make these into separate small PRs for the individual cases. 

But what do you need on testing? I'm factoring this out from our closed code, where I do a bunch more testing of the DOM code using jest/jsdom and mocked MutationObservers. That seems out of line with the current test platform. I could try using `mocha-jsdom` to add tests if needed, or I could just use good old-fashioned manual testing.

**Comment by josteink** [comment]
> For clarity, I should probably make a new issue to make a clean break from the inconclusive discussions in this one. Does that make sense? 

Please do.
